### PR TITLE
FR and IT implementations of national check digit validation

### PR DESCRIPTION
**Pull request by Greybird**
Hi,

This PR is a first proposal to implement #7.
I only implemented and tested IT and FR algorithm.

Before going further, I would like to get feedback from you to ensure the design fits you, and to get additional advises and guidance you might think necessary.

Depending on your feedback, I will adapt and / or implement other countries schemes. 

Regards,

### CODE REVIEW

**Comment by skwasjer** [comment]
Thanks for the PR. 

Here are some of my design goals/considerations:
- It must be opt-in at least for the foreseeable future, so validation will not break while algorithms are implemented. Main reason is a decent number of countries have more than one algorithm. Also, some people may not care for this validation. So I'm thinking of an `IbanOptions` class or smth.
- Potentially, take this moment to open IbanNet up for 'post-built-in-validation' extensibility by defining a public validation interface/rule (or as such maybe even opening up the existing `IIbanValidationRule`). The philosophy here would be allowing custom post validation if so desired (for example, one might want to limit accepted country codes, which is specific business logic). This could hook into previous point, allowing national check digit validation to even be a separate extension lib (at this point in time my personal preference, but I may change my mind).
- Provide an abstraction/separation of national check digits algorithms vs countries. You already sort of have that here, however I would just name the algorithms by their name (Cle Rib and Cin). This makes them reusable for other countries (like Monaco, etc.)
- Provide an abstraction/separation for countries that have multiple national check digits algorithms. An algorithm may have to be selected based on more constraints than just the country code (or all algorithms must be run on a BBAN before considering it invalid). For instance, France I believe also has [SIREN](https://en.wikipedia.org/wiki/SIREN_code), and I know more countries have variations based on different national banks.

That said, overall it looks like a good base to work with. I had something in the works myself with many similarities, I'll push the branch when I have time for you to check out. Perhaps it can be consolidated. 

When I have some more time I'll do a code review.

**Comment by Greybird** [comment]
Hi,

Thanks for the feedback.
I'll try to refine the proposal with regards to your indications, and am looking forward to have a look at your branch.

Your second point appeal to me, as it allows to provide several feedback at once, as well as to indicate if a check was available or not, which is very interesting for national check digits. I also believe that for some countries, there might be so many implementations (DE I think has per bank algorithms ?) that it might not be possible to implement all checks.

(For the record, in France, SIREN has nothing to do with bank accounts, it is an enterprise national number).

**Comment by skwasjer** [comment]
This is by no means ready, but here is the branch (had to consolidate and rebase with some other work locally before I could push):

https://github.com/skwasjer/IbanNet/tree/feature/bban

Originally I intended to look into other functionality as well (as mentioned above) so some scaffolding work was done a while ago.

Check it out and let me know what you think. If you want to add on/consolidate and/or improve, be my guest. (also still needs doc for extension lib etc.)

**Comment by Greybird** [comment]
Hi @skwasjer ,

Finally got some time to take a look at the approach you took to integrate this feature, sorry for the delay!

I must say that I think this is a very good design on the library code, leaving room for extensibility, and also adding a way to get information on issues.
On the BBAN part, the structure you created is far simpler and more readable. I also like the idea that the feature can be added or not depending on the needs.

The only part I am less comfortable with is the `IbanValidationResult` enum (and I was already in my crude proposal).
I think adding a `Custom `value is a way to move forward, but I suppose this should become some construct that could be extensible. I would say that a class hierarchy would allow extensions to reuse core statuses like those related to Illegal characters, and allow for providing new ones.
Library users could handle specialized classes to provide adequate feedback should they need to, and still rely on the base class to catch all issues they might not be aware of.
It looks a lot like `Exception`s actually, but I believe this pattern is working pretty well.

I think I'll work on this branch on implementing more BBAN checks to try to get the broadest range of validations (at least for those that are actually publicly described), at this is what I need most for th e moment. However, rest assured that I am ready to contribute to other aspects like documentation if at some point this work seems worth integrating.

Thanks a lot again for your interest and work on this subject!

**Comment by skwasjer** [comment]
Completely agree. I don't like the enum at all but it is some legacy we have to deal with for now in order to stay (somewhat) compatible to v3.x. While technically even adding `Custom` is a breaking change, those that simply use `IIbanValidator` and check for `IsValid` are not affected by this change. But for a v4 I agree it is now a good idea to refactor out the `enum` completely. I will give it some more thought what is possible to do without introducing too many breaking changes.

I will push a small update of the branch, I actually rebased it earlier today on `master` and added some minor fixes. But overall nothing much changed since. Just force pushed it.

Please do improve where you see fit.

**Comment by skwasjer** [comment]
Moved to separate repo:
https://github.com/skwasjer/IbanNet.Extensions.Bban

**Pull request closed without merging**
