### PR TITLE
feat(localization): add german translation

### PR DESCRIPTION
**Pull request by janro1**
Hi @skwasjer, here is a small PR to add german localisation. I hope it fits like this.

### CODE REVIEW

**Comment by skwasjer** [comment]
Hi @janro1, thanks. Can you add a spot check test case in each test project? Look for a test-file called `LocalizationTests.cs`

For example: https://github.com/skwasjer/IbanNet/blob/main/test/IbanNet.Tests/LocalizationTests.cs

**Comment by janro1** [comment]
Hi @skwasjer, I've added the tests.

**Comment by janro1** [comment]
@skwasjer could you maybe do a release with this included? My current project is waiting for the german localisation.

**Comment by skwasjer** [comment]
Should be available in about 30min: [v5.12.0](https://github.com/skwasjer/IbanNet/releases/tag/5.12.0)

**Pull request merged**
